In [1]:
import torch

In [2]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [3]:
a + b

tensor([[2, 1, 5],
        [5, 4, 8]])

In [5]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
a + b_expanded

tensor([[2, 1, 5],
        [5, 4, 8]])

In [6]:
a = torch.tensor(
    [
        [-1, 1],
        [1, 1],
    ]
)

In [7]:
a + 1

tensor([[0, 2],
        [2, 2]])

In [8]:
a * 2

tensor([[-2,  2],
        [ 2,  2]])

In [9]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1, 2],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


In [10]:
b_expanded = torch.tensor(
    [
        [1, -1, 2],
        [1, -1, 2],
    ]
)
print(b_expanded.shape)

torch.Size([2, 3])


In [11]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1],
)

print(f'a의 shape: {a.shape}')
print(f'b의 shape: {b.shape}')

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([2])


In [ ]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [12]:
import numpy as np
import torch

tensor0 = torch.tensor(
    [
        [1, 1],
        [-1, -1]
    ]
)
tensor1 = torch.tensor(
    [
        [1, 1],
        [0, 0]
    ]
)
tensor2 = torch.tensor(
    [
        [1, -1],
        [1, -1]
    ]
)

add_tensor=tensor0+tensor1
multi = add_tensor@tensor2

# 테스트 코드
print(multi)

tensor([[ 4, -4],
        [-2,  2]])


In [14]:
np_array=np.array(multi)
np_array

array([[ 4, -4],
       [-2,  2]])