In [ ]:
import numpy as np
import pandas as pd

import torch
from torch.utils.data import Dataset

In [ ]:
abalone_df = pd.read_csv(
    'https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv',
    names=['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
           'Viscera weight', 'Shell weight', 'Age']
)

input_data = abalone_df.drop(columns=['Age']).to_numpy().astype(np.float32)
target_data = abalone_df['Age'].to_numpy().astype(np.float32)

class AbaloneDataset(Dataset):
    def __init__(self, input_data, target_data):
        self.input_data = input_data
        self.target_data = target_data

    def __len__(self):
        return len(self.input_data)

    def __getitem__(self, index):
        input_tensor = torch.tensor(self.input_data[index])
        target_tensor = torch.tensor(self.target_data[index])

        return input_tensor, target_tensor

In [ ]:
#80:10:10으로 데이터 분할하기
train_size = int(len(input_data) * 0.8)
val_size = int(len(input_data) * 0.1)

train_inputs = input_data[:train_size]
train_targets = target_data[:train_size]

val_inputs = input_data[train_size:train_size + val_size]
val_targets = target_data[train_size:train_size + val_size]

test_inputs = input_data[train_size + val_size:]
test_targets = target_data[train_size + val_size:]

In [ ]:
train_dataset = AbaloneDataset(train_inputs, train_targets)
val_dataset = AbaloneDataset(val_inputs, val_targets)
test_dataset = AbaloneDataset(test_inputs, test_targets)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [ ]:
scaler.fit(train_inputs)

train_inputs_scaled = scaler.transform(train_inputs)
val_inputs_scaled = scaler.transform(val_inputs)
test_inputs_scaled = scaler.transform(test_inputs)

In [ ]:
print(val_inputs_scaled.mean(axis=0))
print(val_inputs_scaled.std(axis=0))

[-0.06474356 -0.05857919 -0.04376053 -0.0598059  -0.04299596 -0.0507045
 -0.06344681]
[1.0586624  1.0502188  0.9332286  0.9754747  0.9662012  0.97565734
 0.9900307 ]


In [ ]:
train_dataset = AbaloneDataset(train_inputs_scaled, train_targets)
val_dataset = AbaloneDataset(val_inputs_scaled, val_targets)
test_dataset = AbaloneDataset(test_inputs_scaled, test_targets)

In [ ]:
train_data = train_dataset[0]
print(train_data[0])
print(train_data[1])

tensor([-0.7383, -0.7264, -0.6794, -1.0061, -1.0062, -0.9373, -1.0149])
tensor(7.)


In [ ]:
scaler.inverse_transform([train_data[0]])

array([[0.435     , 0.33500001, 0.11      , 0.33399999, 0.13549999,
        0.0775    , 0.09649999]])

In [ ]:
train_inputs[0]

array([0.435 , 0.335 , 0.11  , 0.334 , 0.1355, 0.0775, 0.0965],
      dtype=float32)