In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

import torch
from torch.utils.data import Dataset

In [ ]:
abalone_df = pd.read_csv(
    'https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv',
    names=['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
           'Viscera weight', 'Shell weight', 'Age']
)

input_data = abalone_df.drop(columns=['Age']).to_numpy().astype(np.float32)
target_data = abalone_df['Age'].to_numpy().astype(np.float32)

class AbaloneDataset(Dataset):
    def __init__(self, input_data, target_data):
        self.input_data = input_data
        self.target_data = target_data

    def __len__(self):
        return len(self.input_data)

    def __getitem__(self, index):
        input_tensor = torch.tensor(self.input_data[index])
        target_tensor = torch.tensor(self.target_data[index])

        return input_tensor, target_tensor

train_size = int(len(input_data) * 0.8)
val_size = int(len(input_data) * 0.1)

train_inputs = input_data[:train_size]
train_targets = target_data[:train_size]

val_inputs = input_data[train_size:train_size + val_size]
val_targets = target_data[train_size:train_size + val_size]

test_inputs = input_data[train_size + val_size:]
test_targets = target_data[train_size + val_size:]

scaler = StandardScaler()
scaler.fit(train_inputs)

train_inputs_scaled = scaler.transform(train_inputs)
val_inputs_scaled = scaler.transform(val_inputs)
test_inputs_scaled = scaler.transform(test_inputs)

train_dataset = AbaloneDataset(train_inputs_scaled, train_targets)
val_dataset = AbaloneDataset(val_inputs_scaled, val_targets)
test_dataset = AbaloneDataset(test_inputs_scaled, test_targets)

In [ ]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=8)

In [ ]:
for train_batch in train_dataloader:
    print(f'Input batch\n{train_batch[0]}\n')
    print(f'Target batch\n{train_batch[1]}')
    break

Input batch
tensor([[-0.7383, -0.7264, -0.6794, -1.0061, -1.0062, -0.9373, -1.0149],
        [ 0.5108,  0.4294, -0.3338,  0.0927, -0.0218,  0.2423, -0.0987],
        [ 1.0937,  1.0325,  0.4725,  0.5362,  0.1647,  0.9229,  0.9352],
        [ 0.1777,  0.1782, -0.3338, -0.1230, -0.2937, -0.2840,  0.1509],
        [ 0.1777,  0.1279, -0.2186,  0.1028,  0.0658, -0.1025, -0.0630],
        [ 0.3859,  0.4294,  0.1269, -0.1576, -0.3454,  0.3512, -0.1236],
        [-0.4469, -0.4751, -0.2186, -0.7253, -0.7972, -0.6061, -0.6335],
        [ 0.7190,  0.4294,  1.1637,  0.5128,  0.7086,  0.6234,  0.3897]])

Target batch
tensor([ 7.,  6., 14., 16., 13., 10., 10., 10.])


In [ ]:
train_dataset[7]

(tensor([0.7190, 0.4294, 1.1637, 0.5128, 0.7086, 0.6234, 0.3897]), tensor(10.))

In [ ]:
train_dataloader = DataLoader(train_dataset, batch_size=8, shuffle=True)

In [ ]:
for train_batch in train_dataloader:
    print(f'Input batch\n{train_batch[0]}\n')
    print(f'Target batch\n{train_batch[1]}')
    break

Input batch
tensor([[-0.9465, -0.9274, -0.9098, -1.0752, -1.0578, -1.1188, -0.9900],
        [-1.0298, -0.8772, -1.0250, -0.9776, -0.7432, -1.1597, -1.0827],
        [ 0.8439,  0.8315,  1.0485,  0.6929,  0.7558,  0.6597,  0.7498],
        [ 1.6766,  1.5350,  1.0485,  1.9605,  2.3087,  1.6897,  1.3987],
        [-0.0305,  0.0777,  0.8181, -0.1535, -0.4556, -0.0889,  0.1152],
        [-0.7383, -0.7264, -0.6794, -0.9064, -0.9163, -1.0281, -0.7404],
        [ 0.0944,  0.0274, -0.1034,  0.0682, -0.3320, -0.2568,  0.5787],
        [-1.2380, -1.2792, -1.3705, -1.2736, -1.2444, -1.2050, -1.2395]])

Target batch
tensor([ 8.,  6., 11., 11.,  8., 12., 14.,  8.])


In [ ]:
len(val_dataset)

332

In [ ]:
val_dataloader = DataLoader(val_dataset, batch_size=300)

In [ ]:
for val_batch in val_dataloader:
    print('=============\n')
    print(f'Input batch\n{val_batch[0].shape}\n')
    print(f'Target batch\n{val_batch[1].shape}\n')


Input batch
torch.Size([300, 7])

Target batch
torch.Size([300])


Input batch
torch.Size([32, 7])

Target batch
torch.Size([32])



In [ ]:
val_dataloader = DataLoader(val_dataset, batch_size=300, drop_last=True)

In [ ]:
for val_batch in val_dataloader:
    print('=============\n')
    print(f'Input batch\n{val_batch[0].shape}\n')
    print(f'Target batch\n{val_batch[1].shape}\n')


Input batch
torch.Size([300, 7])

Target batch
torch.Size([300])



#### DataLoader 만들기

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

import torch
from torch.utils.data import Dataset, DataLoader

# 데이터 불러오기
cal_housing = datasets.fetch_california_housing()
input_data = cal_housing.data.astype(np.float32)
target_data = cal_housing.target.astype(np.float32)

# CaliforniaHousingDataset 클래스 정의
class CaliforniaHousingDataset(Dataset):
    def __init__(self, input_data, target_data):
        self.input_data = input_data
        self.target_data = target_data

    def __len__(self):
        return len(self.input_data)

    def __getitem__(self, index):
        input_tensor = torch.tensor(self.input_data[index])
        target_tensor = torch.tensor(self.target_data[index])
        return input_tensor, target_tensor

# 학습/검증/테스트 분할
train_size = int(len(input_data) * 0.8)
val_size = int(len(input_data) * 0.1)

train_inputs = input_data[:train_size]
train_targets = target_data[:train_size]

val_inputs = input_data[train_size:train_size + val_size]
val_targets = target_data[train_size:train_size + val_size]

test_inputs = input_data[train_size + val_size:]
test_targets = target_data[train_size + val_size:]

# 학습 입력 데이터 기준 표준화
scaler = StandardScaler()
scaler.fit(train_inputs)

train_inputs_scaled = scaler.transform(train_inputs)
val_inputs_scaled = scaler.transform(val_inputs)
test_inputs_scaled = scaler.transform(test_inputs)

# Dataset 객체 생성
train_dataset = CaliforniaHousingDataset(train_inputs_scaled, train_targets)
val_dataset = CaliforniaHousingDataset(val_inputs_scaled, val_targets)
test_dataset = CaliforniaHousingDataset(test_inputs_scaled, test_targets)

train_dataloader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=4)
test_dataloader = DataLoader(test_dataset, batch_size=4)


# 테스트 코드
for val_data in val_dataloader:
    print(f'inputs\n{val_data[0]}\n')
    print(f'targets\n{val_data[1]}')
    break

inputs
tensor([[-0.6217,  0.3693,  0.1410, -0.0975, -0.1100,  0.1075,  1.1817, -1.0864],
        [-0.0869, -0.9600,  0.0141, -0.1540,  0.3140,  0.0764,  1.2248, -1.0864],
        [-0.8986, -0.0999, -0.2586, -0.1207,  0.2424,  0.0185,  1.2201, -1.0864],
        [-0.8952,  0.6039, -0.1788, -0.0965, -0.7898, -0.1050,  1.2201, -1.0864]])

targets
tensor([1.6560, 1.2610, 0.9440, 0.9190])
