In [ ]:
import torch

In [ ]:
x = torch.randn(3, 4)
x

tensor([[ 0.0343,  0.6509,  1.8058,  0.1211],
        [-0.8236,  0.9915, -0.4275,  1.8439],
        [-0.5170, -0.7771, -1.0254, -0.0102]])

In [ ]:
res0 = x.reshape(2, 6)
res0

tensor([[ 0.0343,  0.6509,  1.8058,  0.1211, -0.8236,  0.9915],
        [-0.4275,  1.8439, -0.5170, -0.7771, -1.0254, -0.0102]])

In [ ]:
x.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [ ]:
res1 = x.reshape(-1, 2, 3)
res1.size()
''' -1을 넣으면 나머지 두개를 이용해 -1자리는 추론을 통해 정해짐'''

torch.Size([2, 2, 3])

In [ ]:
x.reshape(-1)

tensor([ 0.0343,  0.6509,  1.8058,  0.1211, -0.8236,  0.9915, -0.4275,  1.8439,
        -0.5170, -0.7771, -1.0254, -0.0102])

In [ ]:
x = torch.randn(2, 3, 4)
permuted = x.permute(2, 0, 1)
'''permute는 차원의 인덱스를 입력
2가 0번 자리에 들어갔으니까, 2번 차원이 0번 차원이 됨'''

In [ ]:
permuted.size()

torch.Size([4, 2, 3])

In [ ]:
x = torch.randn(1, 28, 1, 28)

In [ ]:
result0 = x.squeeze()
result0.size()
'''squeeze 메서도 사용하면 크기가 1인 차원 사라지는 경우'''

torch.Size([28, 28])

In [ ]:
result1 = x.squeeze(2)
result1.size()
'''인덱스가 2번 = 3번째 차원이 사라짐'''

torch.Size([1, 28, 28])

In [ ]:
x = torch.randn(28, 28)

In [ ]:
result0 = x.unsqueeze(0)
result0.size()

torch.Size([1, 28, 28])

In [ ]:
result1 = x.unsqueeze(1)
result1.size()

torch.Size([28, 1, 28])