In [ ]:
import torch
import torch.nn as nn

In [ ]:
class FullyConnectedLayer:
    def __init__(self, input_dim, output_dim):
        self.weights = torch.randn(input_dim, output_dim) * 0.01
        self.bias = torch.zeros(output_dim)

    def forward(self, x):
        return x @ self.weights + self.bias

layer = FullyConnectedLayer(8, 4)

x = torch.randn(2, 8)
layer.forward(x)

tensor([[-0.0295,  0.0479,  0.0146, -0.0392],
        [ 0.0391,  0.0286, -0.0001, -0.0495]])

In [ ]:
layer = nn.Linear(in_features=8, out_features=4)

In [ ]:
x = torch.randn(2, 8)
y = layer(x)
y

tensor([[-0.8753,  1.2362,  0.7664,  0.4285],
        [ 0.1967,  0.8272,  0.6014,  0.0913]], grad_fn=<AddmmBackward0>)

In [ ]:
x = torch.randn(8)
y = layer(x)
y

tensor([-0.5417,  0.5424,  1.1398, -1.4022], grad_fn=<ViewBackward0>)

In [ ]:
x = torch.randn(1, 8)
y = layer(x)
y

tensor([[ 0.5518, -0.7699, -0.5280, -0.1341]], grad_fn=<AddmmBackward0>)

#### 활성화 함수

In [ ]:
relu = nn.ReLU()
softmax = nn.Softmax()

In [ ]:
x = torch.randn(1, 4)
y = relu(x)

print(f'input: {x}')
print(f'output: {y}')

input: tensor([[-1.6660, -0.2195, -0.1424, -1.7401]])
output: tensor([[0., 0., 0., 0.]])


#### 손실함수

In [ ]:
loss_mse = nn.MSELoss()
loss_ce = nn.CrossEntropyLoss()