In [ ]:
import torch
import torch.nn as nn

In [ ]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(8, 4)
        self.linear1 = nn.Linear(4, 6)
        self.linear2 = nn.Linear(6, 3)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.linear0(x))
        x = self.relu(self.linear1(x))
        y = self.linear2(x)

        return y

model = MyModel()

In [ ]:
print(model)

MyModel(
  (linear0): Linear(in_features=8, out_features=4, bias=True)
  (linear1): Linear(in_features=4, out_features=6, bias=True)
  (linear2): Linear(in_features=6, out_features=3, bias=True)
  (relu): ReLU()
)


In [ ]:
list(model.children())

[Linear(in_features=8, out_features=4, bias=True),
 Linear(in_features=4, out_features=6, bias=True),
 Linear(in_features=6, out_features=3, bias=True),
 ReLU()]

In [ ]:
for child in model.children():
    print(child)

Linear(in_features=8, out_features=4, bias=True)
Linear(in_features=4, out_features=6, bias=True)
Linear(in_features=6, out_features=3, bias=True)
ReLU()


In [ ]:
for named_child in model.named_children():
    print(named_child)

('linear0', Linear(in_features=8, out_features=4, bias=True))
('linear1', Linear(in_features=4, out_features=6, bias=True))
('linear2', Linear(in_features=6, out_features=3, bias=True))
('relu', ReLU())


In [ ]:
for param in model.parameters():
    print(param)
    print()

Parameter containing:
tensor([[-0.2867,  0.0634,  0.3029,  0.1412,  0.0021, -0.2499,  0.1904, -0.2439],
        [ 0.0481, -0.2940,  0.3036, -0.1374, -0.3034, -0.1377, -0.3061, -0.0791],
        [-0.2205,  0.1722,  0.1296, -0.0648,  0.3406, -0.0851, -0.0382,  0.3237],
        [ 0.0892,  0.0058,  0.3045,  0.2490, -0.1744, -0.0129, -0.3164,  0.2202]],
       requires_grad=True)

Parameter containing:
tensor([ 0.3225,  0.0372, -0.2570, -0.2488], requires_grad=True)

Parameter containing:
tensor([[ 0.0174,  0.3554,  0.1081,  0.2524],
        [-0.2381,  0.0920, -0.1062,  0.3173],
        [ 0.4664, -0.3360,  0.3415,  0.3839],
        [ 0.4124, -0.0073,  0.0874, -0.1125],
        [ 0.0644,  0.1333,  0.3157,  0.2501],
        [-0.1672, -0.4663, -0.4388,  0.4758]], requires_grad=True)

Parameter containing:
tensor([0.0372, 0.2609, 0.2763, 0.1072, 0.0033, 0.1264], requires_grad=True)

Parameter containing:
tensor([[ 0.0531,  0.1588,  0.1473, -0.1062, -0.2250, -0.0505],
        [ 0.2605, -0.1927, 

In [ ]:
for named_param in model.named_parameters():
    print(named_param)
    print()

('linear0.weight', Parameter containing:
tensor([[-0.2867,  0.0634,  0.3029,  0.1412,  0.0021, -0.2499,  0.1904, -0.2439],
        [ 0.0481, -0.2940,  0.3036, -0.1374, -0.3034, -0.1377, -0.3061, -0.0791],
        [-0.2205,  0.1722,  0.1296, -0.0648,  0.3406, -0.0851, -0.0382,  0.3237],
        [ 0.0892,  0.0058,  0.3045,  0.2490, -0.1744, -0.0129, -0.3164,  0.2202]],
       requires_grad=True))

('linear0.bias', Parameter containing:
tensor([ 0.3225,  0.0372, -0.2570, -0.2488], requires_grad=True))

('linear1.weight', Parameter containing:
tensor([[ 0.0174,  0.3554,  0.1081,  0.2524],
        [-0.2381,  0.0920, -0.1062,  0.3173],
        [ 0.4664, -0.3360,  0.3415,  0.3839],
        [ 0.4124, -0.0073,  0.0874, -0.1125],
        [ 0.0644,  0.1333,  0.3157,  0.2501],
        [-0.1672, -0.4663, -0.4388,  0.4758]], requires_grad=True))

('linear1.bias', Parameter containing:
tensor([0.0372, 0.2609, 0.2763, 0.1072, 0.0033, 0.1264], requires_grad=True))

('linear2.weight', Parameter containi

In [ ]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()
        self.block = MyModel()
        self.linear = nn.Linear(3, 4)

    def forward(self, x):
        x = self.block(x)
        return self.linear(x)

model2 = MyModel2()

In [ ]:
print(model2)

MyModel2(
  (block): MyModel(
    (linear0): Linear(in_features=8, out_features=4, bias=True)
    (linear1): Linear(in_features=4, out_features=6, bias=True)
    (linear2): Linear(in_features=6, out_features=3, bias=True)
    (relu): ReLU()
  )
  (linear): Linear(in_features=3, out_features=4, bias=True)
)


In [ ]:
for named_child in model2.named_children():
    print(named_child)

('block', MyModel(
  (linear0): Linear(in_features=8, out_features=4, bias=True)
  (linear1): Linear(in_features=4, out_features=6, bias=True)
  (linear2): Linear(in_features=6, out_features=3, bias=True)
  (relu): ReLU()
))
('linear', Linear(in_features=3, out_features=4, bias=True))


In [ ]:
for named_param in model2.named_parameters():
    print(named_param)
    print()

('block.linear0.weight', Parameter containing:
tensor([[ 0.0708, -0.1850,  0.1424, -0.0556, -0.0364, -0.0917,  0.0493,  0.1708],
        [ 0.2655, -0.1487, -0.2954,  0.0562,  0.1646, -0.1647,  0.3045, -0.1083],
        [ 0.3468,  0.2206,  0.0010,  0.2297, -0.1734,  0.0412,  0.1665,  0.2988],
        [ 0.0744,  0.0501, -0.3250,  0.3114, -0.2622,  0.2378, -0.2194, -0.0879]],
       requires_grad=True))

('block.linear0.bias', Parameter containing:
tensor([ 0.3189, -0.1099,  0.3228,  0.2936], requires_grad=True))

('block.linear1.weight', Parameter containing:
tensor([[ 0.4854,  0.4574, -0.3030, -0.2038],
        [-0.3366, -0.1054, -0.0813,  0.2881],
        [-0.2300,  0.3278,  0.0927, -0.1234],
        [ 0.0051, -0.4376, -0.3120,  0.3941],
        [-0.3858,  0.0129, -0.4633,  0.1191],
        [ 0.3270,  0.0544, -0.3125, -0.4413]], requires_grad=True))

('block.linear1.bias', Parameter containing:
tensor([-0.0448,  0.3153,  0.1633, -0.2693,  0.4188, -0.3627],
       requires_grad=True))



#### 회귀 모델 만들기 실습

In [ ]:
import torch
import torch.nn as nn

class CaliforniaHousingModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear0 = nn.Linear(8, 16)
        self.linear1 = nn.Linear(16, 32)
        self.linear2 = nn.Linear(32, 1)
        #nn.Linear(in_feature, out_feature)의미
        self.relu = nn.ReLU()

    def forward(self, x):
        # h0_0 = self.linear0(x)
        # h0_1 = self.relu(h0_0)

        # h1_0 = self.linear1(h0_1)
        # h1_1 = self.relu(h1_0)

        # y = self.linear2(h1_1)

        x = self.relu(self.linear0(x))
        x = self.relu(self.linear1(x))
        y = self.linear2(x)

        return y

# 테스트 코드
model = CaliforniaHousingModel()
for child in model.children():
    print(child)

Linear(in_features=8, out_features=16, bias=True)
Linear(in_features=16, out_features=32, bias=True)
Linear(in_features=32, out_features=1, bias=True)
ReLU()
